# Generated as the initial schema for the Movizo API.
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("username", models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="username")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("role", models.CharField(choices=[("viewer", "Viewer"), ("moderator", "Moderator"), ("admin", "Admin"), ("superadmin", "Super Admin")], default="viewer", max_length=16)),
                ("membership", models.CharField(choices=[("free", "Free"), ("standard", "Standard"), ("premium", "Premium")], default="free", max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended")], default="active", max_length=16)),
                ("avatar_url", models.URLField(blank=True)),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"verbose_name": "user", "verbose_name_plural": "users", "abstract": False},
            managers=[("objects", django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(name="ContactMessage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("email", models.EmailField(max_length=254)), ("subject", models.CharField(max_length=255)), ("message", models.TextField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("handled_at", models.DateTimeField(blank=True, null=True))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="Genre", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("slug", models.SlugField(blank=True, max_length=90, unique=True)), ("description", models.TextField(blank=True)), ("image_url", models.URLField(blank=True)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Title", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=255)), ("slug", models.SlugField(blank=True, max_length=270, unique=True)), ("kind", models.CharField(choices=[("movie", "Movie"), ("series", "Series")], max_length=10)), ("year", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)])), ("rating", models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])), ("season_count", models.PositiveSmallIntegerField(default=1)), ("status", models.CharField(choices=[("ongoing", "Ongoing"), ("completed", "Completed")], default="ongoing", max_length=12)), ("studio", models.CharField(blank=True, max_length=160)), ("synopsis", models.TextField(blank=True)), ("poster_url", models.URLField(blank=True)), ("banner_url", models.URLField(blank=True)), ("trailer_url", models.URLField(blank=True)), ("video_url", models.URLField(blank=True)), ("trending", models.BooleanField(default=False)), ("view_count", models.PositiveBigIntegerField(default=0)), ("is_published", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("genres", models.ManyToManyField(blank=True, related_name="titles", to="api.genre"))], options={"ordering": ["-created_at", "name"]}),
        migrations.CreateModel(name="Episode", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("season_number", models.PositiveSmallIntegerField(default=1)), ("number", models.PositiveSmallIntegerField()), ("name", models.CharField(max_length=255)), ("duration_seconds", models.PositiveIntegerField(default=0)), ("synopsis", models.TextField(blank=True)), ("thumbnail_url", models.URLField(blank=True)), ("video_url", models.URLField(blank=True)), ("published_at", models.DateTimeField(blank=True, null=True)), ("title", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="api.title"))], options={"ordering": ["season_number", "number"]}),
        migrations.CreateModel(name="WatchList", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("title", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watchlisted_by", to="api.title")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watchlist_entries", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="WatchProgress", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("position_seconds", models.PositiveIntegerField(default=0)), ("progress_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])), ("updated_at", models.DateTimeField(auto_now=True)), ("episode", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="progress_entries", to="api.episode")), ("title", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress_entries", to="api.title")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watch_progress", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-updated_at"]}),
        migrations.CreateModel(name="Report", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("target_type", models.CharField(choices=[("comment", "Comment"), ("title", "Title"), ("profile", "Profile")], max_length=12)), ("target_label", models.CharField(max_length=255)), ("reason", models.CharField(max_length=255)), ("details", models.TextField(blank=True)), ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=10)), ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved"), ("dismissed", "Dismissed")], default="open", max_length=12)), ("created_at", models.DateTimeField(auto_now_add=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)), ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submitted_reports", to=settings.AUTH_USER_MODEL)), ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_reports", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="AuditLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("action", models.CharField(max_length=120)), ("target", models.CharField(max_length=255)), ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="PlatformSetting", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("key", models.SlugField(max_length=80, unique=True)), ("value", models.JSONField(default=dict)), ("updated_at", models.DateTimeField(auto_now=True)), ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={"ordering": ["key"]}),
        migrations.AddConstraint(model_name="episode", constraint=models.UniqueConstraint(fields=("title", "season_number", "number"), name="unique_episode_number")),
        migrations.AddConstraint(model_name="watchlist", constraint=models.UniqueConstraint(fields=("user", "title"), name="unique_watchlist_title")),
        migrations.AddConstraint(model_name="watchprogress", constraint=models.UniqueConstraint(fields=("user", "title"), name="unique_title_progress")),
    ]
