# Generated by Django 5.2.17 on 2026-09-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deactivate_legacy_public_accounts(apps, schema_editor):
    """Preserve historical rows but prevent old viewer/moderator logins."""
    User = apps.get_model("api", "User")
    User.objects.exclude(role__in=["admin", "superadmin"]).update(is_active=False, is_staff=False)


def restore_legacy_public_accounts(apps, schema_editor):
    # Never reactivate accounts automatically during a rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin')], default='admin', max_length=16),
        ),
        migrations.RunPython(deactivate_legacy_public_accounts, restore_legacy_public_accounts),
        migrations.CreateModel(
            name='AdminTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField()),
                ('drift', models.IntegerField(default=0)),
                ('last_verified_step', models.BigIntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
